export const SWITCH_LOADER = 'SWITCH_LOADER';
export const SHOW_SELECTED = "SHOW_SELECTED";
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_VIEWPORT ="SET_VIEWPORT";
export const FETCH_IMAGES = 'FETCH_IMAGES';
